# Generated by Django 6.0.6 on 2026-06-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Detección')),
                ('objeto_detectado', models.CharField(max_length=100, verbose_name='Objeto Detectado')),
            ],
        ),
    ]
